package com.michistore.ventas.view;

/**
 *
 * @author jhon_
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedor = new javax.swing.JDesktopPane();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuItemCuenta = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        menuItemCategoria = new javax.swing.JMenuItem();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemProducto = new javax.swing.JMenuItem();
        menuSales = new javax.swing.JMenu();
        menuItemNewSale = new javax.swing.JMenuItem();
        menuItemReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bundles/text"); // NOI18N
        setTitle(bundle.getString("appname")); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        contenedor.setMinimumSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(contenedor, gridBagConstraints);

        lblMessage.setText(bundle.getString("main.message")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblMessage, gridBagConstraints);

        menuInicio.setText(bundle.getString("main.menu.home")); // NOI18N

        menuItemCuenta.setText(bundle.getString("main.menu.account")); // NOI18N
        menuInicio.add(menuItemCuenta);

        menuItemSalir.setText(bundle.getString("main.menu.close")); // NOI18N
        menuInicio.add(menuItemSalir);

        jMenuBar1.add(menuInicio);

        menuMantenimiento.setText(bundle.getString("main.menu.maintenance")); // NOI18N

        menuItemCategoria.setText(bundle.getString("main.menu.maintenance.categories")); // NOI18N
        menuMantenimiento.add(menuItemCategoria);

        menuItemCliente.setText(bundle.getString("main.menu.maintenance.customers")); // NOI18N
        menuMantenimiento.add(menuItemCliente);

        menuItemProducto.setText(bundle.getString("main.menu.maintenance.products")); // NOI18N
        menuMantenimiento.add(menuItemProducto);

        jMenuBar1.add(menuMantenimiento);

        menuSales.setText(bundle.getString("main.menu.sales")); // NOI18N

        menuItemNewSale.setText(bundle.getString("main.menu.sales.new")); // NOI18N
        menuSales.add(menuItemNewSale);

        menuItemReport.setText(bundle.getString("main.menu.sales.report")); // NOI18N
        menuSales.add(menuItemReport);

        jMenuBar1.add(menuSales);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane contenedor;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel lblMessage;
    public javax.swing.JMenu menuInicio;
    public javax.swing.JMenuItem menuItemCategoria;
    public javax.swing.JMenuItem menuItemCliente;
    public javax.swing.JMenuItem menuItemCuenta;
    public javax.swing.JMenuItem menuItemNewSale;
    public javax.swing.JMenuItem menuItemProducto;
    public javax.swing.JMenuItem menuItemReport;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JMenu menuMantenimiento;
    public javax.swing.JMenu menuSales;
    // End of variables declaration//GEN-END:variables
}
